### ISSUE TITLE
Panic Ejections may be showing as multiple kills

### ISSUE THREAD

**Issue by IceRaptor** [BattletechModders/PanicSystem#6] opened 2020-06-10 17:01 UTC
As per #rogueticket-456:

> Just played a duo duel and killed one+ejected 1 enemy mech
the mission report shows 1 kill+3 ejections

[cleaned_output_log.txt](https://github.com/BattletechModders/PanicSystem/files/4760078/cleaned_output_log.txt)
![unknown](https://user-images.githubusercontent.com/96743/84296801-8b224600-ab1a-11ea-9bcf-2d515f87c266.png)

**Comment by fmnatic** [comment] 2020-06-18 17:26
I can reproduce this on duo duels, even when there are no ejections (2 kills). Seems to be an attempt to make the kills+ejections total to 4 somewhere. Don't see anything relevant in panicsystem.
This may be a duel implementation thing?

**Comment by fmnatic** [comment] 2020-06-20 06:35
Possibly related in Panic system 

> // TODO count kills recorded on pilot history so it's not applied twice

**Comment by fmnatic** [comment] 2020-06-20 09:17
added double counting check, under test.

**Comment by fmnatic** [comment] 2020-06-21 14:55
bug fixed in the PanicSystem UI layer. Each pilot was getting the ejection count of the previous pilot added up.

**Comment by xeryx01** [comment] 2020-07-02 09:06
The main problem is that pilots not getting kills, are showing them. It is almost a display glitch but there must be something more to it, but it worked before!
![nokill](https://user-images.githubusercontent.com/45599120/86339563-f9859000-bc10-11ea-8a08-63f7b76761c9.PNG)

**Comment by fmnatic** [comment] 2020-07-02 09:19
Yeah , no idea at what point the bug was introduced, but its been there for the couple of months since i've been playing.

 I have it fixed on my fork. Whats happening is for pilots with zero ejections, the number from the last pilot with ejections is used, even across missions.

**Comment by xeryx01** [comment] 2020-07-08 16:07
THank you fmnatic for updating the mod, it seem salso the delay that was occuiring when ejection occurs is also gone

**Comment by fmnatic** [comment] 2020-08-19 10:06
this was fixed in 4.1.0

**Closed as completed by fmnatic** 2020-08-19 10:06 UTC
